const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
};

export default UserActionTypes;